# ./cloudflare-config/config.yml

# 從 'cloudflared tunnel create' 指令取得的 Tunnel UUID
tunnel: 61dabd6c-7c28-4c76-a2fa-3a010c2f6425 # <== 請換成您的 Tunnel UUID

# 指向容器內 Tunnel 憑證檔案的路徑
# 因為我們會將 ./cloudflare-config 掛載到容器內的 /etc/cloudflared
# 所以這裡的路徑是 /etc/cloudflared/檔名.json
credentials-file: /cloudflare/61dabd6c-7c28-4c76-a2fa-3a010c2f6425.json # <== 請換成您的 .json 檔名

# 強制使用 HTTP/2 而非 QUIC 協議。
# protocol: http2

# Ingress 規則：定義外部流量如何路由到內部服務
ingress:
  # 規則一：將前端流量導向 frontend 服務的 80 port
  # 選擇一個子網域，例如 app.yourdomain.com
  - hostname: dev-sam2f.jmprohub.com        # <== 修改成您要給前端使用的公開網址
    service: http://frontend:80           # 指向 docker-compose 中的 frontend 服務及其內部 port 80

  # 規則二：將後端 API 流量導向 backend 服務的 5000 port
  # 選擇另一個子網域，例如 api.yourdomain.com
  - hostname: dev-sam2b.jmprohub.com         # <== 修改成您要給後端使用的公開網址
    service: http://backend:5000          # 指向 docker-compose 中的 backend 服務及其內部 port 5000

  # 規則三：必要的回退規則，處理不匹配的請求
  - service: http_status:404


